name: Deploy to Juno

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm ci

      - name: Prepare Juno
        run: npm run code:prepare-deploy
        env:
          JUNO_TOKEN: ${{ secrets.JUNO_TOKEN }}
          JUNO_SATELLITE_ID: ${{ vars.JUNO_SATELLITE_ID }}

      - name: Deploy to Juno
        uses: junobuild/juno-action@main
        with:
          args: deploy
        env:
          JUNO_TOKEN: ${{ secrets.JUNO_TOKEN }}
          JUNO_SATELLITE_ID: ${{ vars.JUNO_SATELLITE_ID }}
